// Static NIP name registry — keeps us dependency-free.
// Source: https://github.com/nostr-protocol/nips

export const NIP_NAMES: Record<number, string> = {
  1: "Basic protocol flow & events",
  2: "Follow list",
  3: "OpenTimestamps attestations",
  4: "Encrypted direct messages (deprecated)",
  5: "Mapping Nostr keys to DNS identifiers",
  6: "Basic key derivation from mnemonic",
  7: "window.nostr capability for web clients",
  9: "Event deletion request",
  10: "Conventions on e and p tags in text events",
  11: "Relay information document",
  13: "Proof of work",
  14: "Subject tag in text events",
  15: "Nostr Marketplace (for resilient markets)",
  17: "Private direct messages",
  18: "Reposts",
  19: "bech32-encoded entities",
  21: "nostr: URI scheme",
  22: "Comment",
  23: "Long-form content",
  24: "Extra metadata fields and tags",
  25: "Reactions",
  26: "Delegated event signing",
  27: "Text note references",
  28: "Public chat",
  29: "Relay-based groups",
  30: "Custom emoji",
  31: "Dealing with unknown events",
  32: "Labeling",
  34: "git stuff",
  35: "Torrents",
  36: "Sensitive content / content warning",
  38: "User statuses",
  39: "External identities in profiles",
  40: "Expiration timestamp",
  42: "Authentication of clients to relays",
  44: "Versioned encryption",
  45: "Counting results",
  46: "Nostr Connect",
  47: "Wallet Connect",
  48: "Proxy tags",
  49: "Private key encryption",
  50: "Search capability",
  51: "Lists",
  52: "Calendar events",
  53: "Live activities",
  54: "Wiki",
  55: "Android signer application",
  56: "Reporting",
  57: "Lightning zaps",
  58: "Badges",
  59: "Gift wrap",
  60: "Zap splits",
  64: "Chess (PGN)",
  65: "Relay list metadata",
  70: "Protected events",
  71: "Video events",
  72: "Moderated communities",
  73: "External content IDs",
  75: "Zap goals",
  78: "Application-specific data",
  84: "Highlights",
  89: "Recommended application handlers",
  90: "Data vending machines",
  92: "Media attachments",
  94: "File metadata",
  96: "HTTP file storage integration",
  98: "HTTP Auth",
  99: "Classified listings",
};
